[build-system]
requires = ["hatchling>=1.5.0", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "fetchez"
description = "Geo-Spatial Data Fetching"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
dynamic = ["version"]
authors = [
    {name = "Matthew Love", email = "matthew.love@colorado.edu"},
    {name = "Christopher Amante", email = "christopher.amante@colorado.edu"},
    {name = "Elliot Lim", email = "elliot.lim@colorado.edu"},
    {name = "Michael MacFerrin", email = "michael.macferrin@colorado.edu"},
    {name = "Matt Fisher", email = "mfisher87@gmail.com"},
]
maintainers = [
    {name = "Matthew Love", email = "matthew.love@colorado.edu"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: GIS",
]

dependencies = [
    "requests[security]",
    "lxml",
    "tqdm",
    "pyyaml",
    "click",
    "filelock",
    "pyproj",
    "shapely",
    "pyogrio",
    "rasterio>1.4.0",
]

keywords = ["Geospatial"]

[project.optional-dependencies]
aws = ["boto3"]
bing = ["mercantile"]
earthdata = ["earthaccess>=0.9.0"]
stac = ["pystac", "pystac_client", "planetary_computer"]
marine = ["copernicusmarine"]
# jupyter = ["jupyterlab", "ipyleaflet", "ipywidgets"]

full = ["fetchez[aws,bing,earthdata,stac]"]

[dependency-groups]
dev = [
    "pre-commit",
    "mypy",
    "types-requests>=2.31.0.6",
    "types-tqdm>=4.67.0.20241221",
    # "yamllint"
]
test = [
    "pytest",
    "pytest-cov",
]
docs = [
    "sphinx<9.0.0",  # temp pin for sphinx-click
    "sphinx-autodoc-typehints>=2.0.1",
    # "sphinx-argparse-cli",
    "sphinx-click>=6.0",
    "pydata-sphinx-theme",
    "myst-parser",
]

[project.scripts]
# CLI Entry Points
fetchez_cli = "fetchez._cli:fetchez_cli"
fetchez = "fetchez.cli:cli"

[project.urls]
Homepage = "https://github.com/ciresdem/fetchez"
Issues = "https://github.com/ciresdem/fetchez/issues"


# --- Build configuration ---

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.version]
path = "src/fetchez/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/fetchez"]

[tool.hatch.build.targets.sdist]
include = [
  "src/fetchez",
  "tests",
  "CHANGELOG.md",
  "CITATION.cff",
  "CONTRIBUTING.md",
  "AUTHORS.md",
]
exclude = [
  ".github",
  "examples",
  "scripts",
]


# --- Devtools configuration ---

[tool.mypy]
mypy_path = "src"
packages = ["fetchez"]
python_version = "3.12"
exclude = ["^build/", "^dist/", "^\\.venv/"]
# allow_untyped_globals = true
# strict = true

[[tool.mypy.overrides]]
module = [
    "shapely.*",
    "lxml.*",
    "boto3",
    "botocore.*",
    "mercantile",
    "osgeo",
    "filelock",
    "pyogrio.*",
    "pyogrio.raw",
    "pyproj",
    "sentinelsat",
    "shapefile",
    "yaml",
    "earthaccess.*",
    "pystac",
    "pystac_client",
    "planetary_computer",
    "copernicusmarine",
    "fsspec",
    "fsspec.*",
]
ignore_missing_imports = true
# disable_error_code = ["import-not-found"]

[tool.ruff.lint]
# select = ["ALL"]  # Goal :)
extend-select = [  # Extend the default ruleset:
    "B",
    "F",
    # "S",
    # "G", # logging
    "PTH100",  # os.path.abspath
    "PTH102",  # os.mkdir
    "PTH103",  # os.mkdirs
    "PTH110",  # os.path.exists
    "PTH112",  # os.path.isdir
    # "PTH119",  # os.path.basename
    "PTH120",  # os.path.dirname
    # "SIM102",
    "T20",  # flake8-print <https://docs.astral.sh/ruff/rules/#flake8-print-t20>
]

[tool.ruff.lint.per-file-ignores]
# Allow print() statements in CLI module where they are expected
"src/fetchez/_cli.py" = ["T201"]
"examples/**/*.py" = ["T201"]
"src/fetchez/hooks/stream_dump.py" = ["T203"] # allow pprint here
"tests/**/*.py" = ["S"]

[tool.pytest.ini_options]
markers = [
    "health: marks tests that require live network access to external APIs (run with '-m health')"
]
filterwarnings = [
    "ignore::pydantic.warnings.PydanticDeprecatedSince20",
    "ignore:.*Support for class-based `config` is deprecated.*",
    "ignore::DeprecationWarning:planetary_computer.*"
]
